config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  get 'imagen', to: 'pages#imagen'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]
  #vista iniciar sesion
  get 'login', to: 'sessions#new'
  #validar inicio de sesion
  post 'login', to: 'sessions#create'
  #cerrar sesion
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimun: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user, :logged_in?

  def current_user
    # Para no acceder a la base de datos constantemente, guardamos el resultado
    # de la busqueda en @current_user mediante ||= , el resto es un if else normal escrito de otra manera 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # Devuelve True o False dependiendo del metodo current_user
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "Necesitas iniciar sesion para realizar esta accion"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    #@article = Article.find(params[:id])
  end

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
    #@article = Article.find(params[:id])
    
  end

  def create
    #render plain: params[:article]
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Articulo creado satisfactoriamente'
    #redirect_to article_path(@article)
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    #@article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = 'Articulo actualizado satisfactoriamente'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "Solo puedes editar tus articulos"
      redirect_to @article
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

  def imagen
    @number = rand(100)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Autentificado correctamente"
      redirect_to user
    else
      flash.now[:alert] = "Error en las credenciales"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Desconectado"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    #@articles = @user.articles
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    #@users = User.all
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Usuario #{@user.username} creado satisfactoriamente"
    #redirect_to article_path(@article)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Información actualizada satisfactoriamente'
      #redirect_to article_path(@article)
      redirect_to @user
    else
      render 'edit'
    end

  end

  def destroy
    # @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "La cuenta y todos sus articulos relacionas eliminados correctamente"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "Solo puedes modificar tu perfil"
      redirect_to @user
    end
  end
   
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_source = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_source, alt: user.username, class: "rounded shadow mx-auto d-block")

  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="mt-4 mb-4">
      <div class="card">
        <div class="card-header">
          <%= link_to article.user.username, user_path(article.user) %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
            <p class="card-text"><%= truncate(article.description, lenght: 50) %></p>
            <% if logged_in? && (current_user == article.user || current_user.admin?)%>
              <a><%= link_to 'Edit', edit_article_path(article),
                :class => "btn btn-primary" %></a>
              <a><%= link_to 'Delete', article_path(article), 
              :class => "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"} %></a>
            <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
          edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class:"shadow p-3 mb-4 bg-white rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label" %><br>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control", placeholder: "Titulo del artículo" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label" %><br>
          <div class="col-10">
            <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Descripción del artículo" %>
          </div>
        </div>

        <div class="form-group row justify-content-center mt-4">
          <%= f.submit class: "btn btn-primary"%>
        </div>
        
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to 'Volver a la lista de articulos', articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Editar artículo</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container mt-4">
  <h1>Lista de artículos</h1>
  <p><%= link_to 'Crear nuevo articulo', new_article_path,
      :class => "btn btn-primary" %></p>
</div>

<div class="pagination justify-content-md-center">
  <%= will_paginate @articles%>
</div>

<%= render 'article' %>

<div class="mb-5 pagination justify-content-md-center">
  <%= will_paginate @articles%>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Crear nuevo artículo</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container mt-4">
  <h1><%= @article.title %></h1>
</div>

<div class="container">
    <div class="mt-4">
      <div class="card">
        <div class="card-header font-italic text-center ">
          <%= @article.user.username %>
        </div>
        <div class="card-body">
          <div class="card-text"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
              <a><%= link_to 'Edit', edit_article_path(@article),
                :class => "btn btn-primary" %></a>
              <a><%= link_to 'Delete', article_path(@article), 
              :class => "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"} %></a>
            <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
    <div class="row justify-content-center mt-5">
      <%= link_to 'Volver a la lista de articulos', articles_path %></p>  
    </div>  
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-3 bg-dark text-white">
  <div class="container text-center"> 
    <small>Copyright &copy; Asociación UNIA 2022 </small>
    <div><small><%= link_to "CUB5", "https://cub5.com", class: "text-white"%></small></div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <% flash.each do |name, msg| %>
        <% if name == 'notice' %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
        <% else %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <% end %>
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" id="brandid" href="#">CUB5</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Inicio', root_path, class: 'nav-link'%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articulos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Artículos', articles_path, class: 'dropdown-item'%>
          <%= link_to 'Blogueros', users_path, class: 'dropdown-item'%>
          <% if logged_in? %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Crear nuevo articulo', new_article_path,
              :class => "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Acerca de', about_path, class: 'nav-link'%>
      </li>

      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Perfil', user_path(current_user), class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
            <%= link_to 'Cerrar Sesión', logout_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar Sesión', login_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', signup_path, class: 'nav-link' %>
        </li>
      <% end %>

      <% if logged_in? && current_user.admin? %>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">ADMIN</a>
        </li>
      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Búsqueda</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test RoR 6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <div id="page-content">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container mt-4">
  <div class="row justify-content-center"></div>
    <div class="col-10">
    </div>
    <h1>About OK!</h1>

    <p><%= link_to 'Volver a inicio', root_path %></p>
  </div>
</div>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron">
      <h1 class="display-4">Poéticamente</h1>
        <p class="lead">Bienvenido al lugar donde las letras inundan y se convierten en tu espacio tiempo.</p>
          <hr class="my-4">
        <p>Esperamos que disfrute de la obra.</p>
        <%= link_to "¡Registrate!", signup_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>

app/views/pages/imagen.html.erb
<%= link_to 'Volver a inicio', root_path %>

 <% if @number < 50%>
  <%= image_tag "test.png", height: 150%>
  <% else %>
  jaja prueba de nuevo

 <% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Los siguientes errores se produjeron al guardar el <%= obj.class.name.downcase %></h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class:"shadow p-3 mb-4 bg-white rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label" %><br>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control", placeholder: "Nombre de usuario" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label" %><br>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label" %><br>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control", placeholder: "Contraseña" %>
          </div>
        </div>

        <div class="form-group row justify-content-center mt-4">
          <%= f.submit(@user.new_record? ? "Registrarse" : "Actualizar", class: "btn btn-primary") %>
        </div>
        
      <% end %>
      <div class="mb-3 row justify-content-center">
        <%= link_to 'Volver a inicio', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edita tu perfil</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Blogeros</h1>

<div class="mt-5 pagination justify-content-md-center">
  <%= will_paginate @users %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <%= user.username %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
            <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to 'Ver perfil', user, class: "btn btn-primary" %>
            <% if logged_in? %>
              <% if current_user == user %> 
                <%= link_to 'Editar perfil', edit_user_path(user), class: "btn btn-primary" %>
              <% end %>
              <% if current_user.admin? %> 
                <%= link_to "Eliminar Usuario", user_path(user), class: "btn btn-outline-danger", 
                    method: :delete, data: { confirm: '¿Estas seguro de eliminar la cuenta?'} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="mb-5 pagination justify-content-md-center">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Registrate en el blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> Perfil de <%= @user.username %></h1>

<%= gravatar_for @user, size:200%>

<% if logged_in? && current_user == @user %>
  <div class="text-center mt-4">
  <%= link_to "Edita tu perfil", edit_user_path(@user), class: "btn btn-outline-info" %>
  <%= link_to "Elimina tu perfil", user_path(@user), class: "btn btn-outline-danger", 
      method: :delete, data: { confirm: '¿Estas seguro de eliminar tu cuenta?'} %>
  </div>
<% end %>

<h3 class="text-center mt-4"> Artículos</h3>

<div class="mt-5 pagination justify-content-md-center">
  <%= will_paginate @articles %>
</div>

<%= render 'articles/article'%>

<div class="mb-5 pagination justify-content-md-center">
  <%= will_paginate @articles %>
</div>